### hello
GET http://localhost:8081/hello
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSIsInJlczIiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJzY29wZTEiLCJzY29wZTIiXSwiZXhwIjoxNzAxNTM4OTQ3LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImZlZmYzZDZkLTQ5NGQtNGMxYi1iYzQwLWZkMjBiNzY5YzJkYiIsImNsaWVudF9pZCI6ImNsaWVudDEifQ.HMOf2tW298Dhttzw01cYHgRyRATGBHjqFUpkBZh0YhZHSHdTIIxViMBff0r_wGP5kkoaOfDje9WZO_jQN-Lk7iIyHi645nk2CJWxymVqi67CfzLPkxlcd-SQX-JSYPp4w60ONN51lPvF1UE7LUPru9jIgW17wYn_gpV3hJuAYfQY8lgHdAKmKrQoy-xLN86ze71dv-zfe--IGDQZOKTgsiyOTnZUJ3IjDnq8f4o1PbMSKVjZZOtO2xjAqg3rkHU17eFRpx7MycAMISmwsTbDTzUamPvgVaYvw3p-XD9BJi7aTxvpPwMCdbshbD9dfemV74IKhFVqeaHqlJqjgF3TCQ

### admin
GET http://localhost:8081/admin
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSIsInJlczIiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJzY29wZTEiLCJzY29wZTIiXSwiZXhwIjoxNzAxNTM4OTQ3LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImZlZmYzZDZkLTQ5NGQtNGMxYi1iYzQwLWZkMjBiNzY5YzJkYiIsImNsaWVudF9pZCI6ImNsaWVudDEifQ.HMOf2tW298Dhttzw01cYHgRyRATGBHjqFUpkBZh0YhZHSHdTIIxViMBff0r_wGP5kkoaOfDje9WZO_jQN-Lk7iIyHi645nk2CJWxymVqi67CfzLPkxlcd-SQX-JSYPp4w60ONN51lPvF1UE7LUPru9jIgW17wYn_gpV3hJuAYfQY8lgHdAKmKrQoy-xLN86ze71dv-zfe--IGDQZOKTgsiyOTnZUJ3IjDnq8f4o1PbMSKVjZZOtO2xjAqg3rkHU17eFRpx7MycAMISmwsTbDTzUamPvgVaYvw3p-XD9BJi7aTxvpPwMCdbshbD9dfemV74IKhFVqeaHqlJqjgF3TCQ