### hello
GET http://localhost:8081/hello
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSIsInJlczIiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJzY29wZTEiLCJzY29wZTIiXSwiZXhwIjoxNzAxNTA2MzAzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImQyNWE0ZmY3LWZiYWUtNDEwZS05OTIzLTYxZGRiMTRkNGE2OCIsImNsaWVudF9pZCI6ImNsaWVudDEifQ.8q59GHZN9DwgBqMeBDWfOIOhAQsRA7HfQt15rNn087o

### admin
GET http://localhost:8081/admin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSIsInJlczIiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJzY29wZTEiLCJzY29wZTIiXSwiZXhwIjoxNzAxNTA2MzAzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImQyNWE0ZmY3LWZiYWUtNDEwZS05OTIzLTYxZGRiMTRkNGE2OCIsImNsaWVudF9pZCI6ImNsaWVudDEifQ.8q59GHZN9DwgBqMeBDWfOIOhAQsRA7HfQt15rNn087o