# 申请授权码流程如下所示：
# 1. 浏览器访问授权服务器的授权端点（/oauth/authorize），http://localhost:8080/oauth/authorize?client_id=client1&response_type=code&scope=scope1&redirect_uri=https://www.baidu.com&state=abc
# 2. 出现登录页面，输入用户名密码，登录成功
# 3. 出现授权页面，点击授权按钮，授权成功
# 4. 浏览器跳转到百度页面，地址栏出现code，复制code

### 授权码模式（使用授权码（code）获取访问令牌（token））
POST http://localhost:8080/oauth/token?client_id=client1&client_secret=123456&grant_type=authorization_code&code=i0zhrA&
    redirect_uri=https://www.baidu.com

### 刷新令牌

POST http://localhost:8080/oauth/token?client_id=client1&client_secret=123456&grant_type=refresh_token&
    refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSIsInJlczIiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJzY29wZTEiLCJzY29wZTIiXSwiYXRpIjoiNzU5N2Y5YzUtNDA2Ny00Y2YxLWJmZjgtNWIyOTE0ZmQyZDAxIiwiZXhwIjoxNzAxOTQwMDYxLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6IjA1YTVjMzFiLTUxYWUtNGM0My05OTIwLWJjMTZlYTM0M2YwYSIsImNsaWVudF9pZCI6ImNsaWVudDEifQ.CmXdtBZ9fFL-MIZ1W7H8YVmVE4hpNyeWA1H-yYAdTNU

# 简化模式 浏览器访问 http://localhost:8080/oauth/authorize?client_id=client1&response_type=token&scope=scope1&redirect_uri=https://www.baidu.com&state=abc

### 密码模式
POST http://localhost:8080/oauth/token?client_id=client1&client_secret=123456&grant_type=password&username=admin&
    password=123456

### 客户端模式
POST http://localhost:8080/oauth/token?client_id=client1&client_secret=123456&grant_type=client_credentials&scope=scope1

### 获取公钥
GET http://localhost:8080/oauth/token_key
