spring:
  rabbitmq:
    host: 42.194.233.222
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1 # 消费者每次只能从队列中预取一条消息，只有等消费者处理完并返回确认后才能继续取下一条消息